twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    reservationType: "@App\\Form\\ReservationType"
    sessionService: "@App\\Session\\SessionService"

when@test:
  twig:
    strict_variables: true
